### ISSUE TITLE
Termios needs a safe constructor

### ISSUE THREAD

**Issue by asomers** [nix-rust/nix#1115]
The only constructor method for `Termios` is the unsafe and undocumented `default_uninit`.  All of the examples use that function.  But not only is it `unsafe`, it also uses `std::mem::uninitialized`, which will be deprecated in Rust 1.38.0.  This will soon be the last remaining use of `std::mem::uninitialized`.

**Comment by asomers** [comment]
ping @Susurrus would you have some time to try fixing this?

**Comment by Susurrus** [comment]
Is there anything to fix? #1158 got rid of `mem::uninitialized()`, and zeroing it seems fine. If anything switching it from `doc(hidden)` to `pub(crate)` seems more useful (same with the below `update_wrapper()` function.

**Comment by asomers** [comment]
Is all zeros actually a valid state for a `libc::termios`?  If so, then zeroing it is ok.  But if not then we should just delete that function and force people to use proper constructors like `tcgetattr`.  Also, we should remove `default_uninit` from the API docs.

**Comment by Susurrus** [comment]
This is effectively a private function because of the `doc(hidden)` (which was the way to do this before `pub(crate)`). That's why I suggested changing it to `pub(crate)` and being done (however this is technically a breaking change). I don't use it in `serialport`, which would likely be one of the only users, so I imagine it won't impact users much.

**Comment by asomers** [comment]
Yeah, I agree with making it `pub(crate)`.  But even though it's currently `#[doc(hidden)]`, it's still used in the API docs (in hidden form), so you'll have to replace it with something or the doc tests will break.
