### ISSUE TITLE
Soundness of FD-related APIs?

### ISSUE THREAD

**Issue by eduardosm** [nix-rust/nix#1225]
nix provides APIs to do some operations with FDs without the need of `unsafe` code, such as `nix::unistd::close` or `nix::unistd::write`.

The documentation of `std::os::unix::io::FromRawFd::from_raw_fd` says:

> This function is also unsafe as the primitives currently returned have the contract that they are the sole owner of the file descriptor they are wrapping. Usage of this function could accidentally allow violating this contract which can cause memory unsafety in code that relies on it being true.

However, the APIs provided by nix seem to allow taking the ownership of a FD without the need of `unsafe` code. For example, you should be the owner of a FD to `close` it.

Regarding `nix::unistd::write`, it allows writing to arbitrary FDs. In the best case, it will fail with a `EBADF`, but in the worst case, it will write into a `mmap`ed FD.

**Comment by asomers** [comment]
Yes, working with `RawFd` is tricky, especially since it implements `Copy`.  Arguably, Rust should've defined `RawFd` as a newtype that doesn't implement `Copy` or `Clone`.  But that horse has left the barn.

> nix provides APIs to do some operations with FDs without the need of `unsafe` code, such as `nix::unistd::close` or `nix::unistd::write`.
> 
> The documentation of `std::os::unix::io::FromRawFd::from_raw_fd` says:
> 
> > This function is also unsafe as the primitives currently returned have the contract that they are the sole owner of the file descriptor they are wrapping. Usage of this function could accidentally allow violating this contract which can cause memory unsafety in code that relies on it being true.

The reason that `FromRawFd::from_raw_fd` is `unsafe` isn't because of anything inherent in `RawFd`, it's because of the structs that implement `FromRawFd`.  For example, `std::fs::File` expects to be the sole owner of its file descriptor, so it can do stuff like close on `drop`.

> 
> However, the APIs provided by nix seem to allow taking the ownership of a FD without the need of `unsafe` code. For example, you should be the owner of a FD to `close` it.

If you create a `RawFd`, then pass that to both `File::from_raw_fd` and `nix::unistd::close` you have indeed created a bug (possibly a memory unsafety bug, but that would depend on the internals of `File`).  But that's why `from_raw_fd` is `unsafe`.  OTOH, if you call `nix::unistd::close` twice on the same `RawFd` you've also created a bug (closing an invalid file descriptor), but there is no risk of memory unsafety.  So even though it's a bug, it doesn't violate Rust's safety guarantees and therefore doesn't need `unsafe`.

> 
> Regarding `nix::unistd::write`, it allows writing to arbitrary FDs. In the best case, it will fail with a `EBADF`, but in the worst case, it will write into a `mmap`ed FD.

The Rust community long ago decided that special operating system interfaces must lay beyond the bounds of the language's safety guarantees.  To do otherwise would produce absurd results.  For example, if you write to `/dev/mem` using the safe standard interfaces in `std::fs` you can produce a segfault.  But that doesn't justify making `std::fs`'s functions all `unsafe`.

I'm gong to close this bug for now because in general there's nothing inherently `unsafe` about handling a `RawFd`.  But it's certainly possible that Nix contains specific uses that ought to be marked `unsafe`.  If you find one, please open a new bug.
