### ISSUE TITLE
undocumented and potentially unnessary unsafe blocks

### ISSUE THREAD

**Issue by matu3ba** [nix-rust/nix#1380]
In [wait.rs](https://github.com/nix-rust/nix/blob/c0c55700df23cf4a8b2d1f0f7f4a06b013dab59a/src/sys/wait.rs#L120-L153) are `#[allow(unused_unsafe)]` annotated blocks and unsafe without explanation.

Looking at the `libc` crate, they use `safe_f` macro rules. I think this should mean that usage of this function is safe (in contrast to f macro rule in libc).

Reason for my request is a global lint rule forbidding unused unsafe.

The functions `exited, exit_status, signaled, term_signal, dumped_core, stopped, stop_signal` are also untested.

What am I missing on this?

**Comment by asomers** [comment]
They're there because libc originally defined those functions as `unsafe`, then later change them into safe functions.  The `#[allow]` directive was necessary in order to allow Nix to build with both old and new versions of libc.  If Nix's minimum version of libc now exceeds the version that made those functions safe (I haven't checked), then please submit a PR removing the directive.

See also #1294 .

**Comment by matu3ba** [comment]
Take a look for example at libc tag [fuchsia](https://github.com/rust-lang/libc/blob/0.2.82/src/fuchsia/mod.rs#L3275-L3311) and all non-windows systems.

newlibc in crate libc has currently no definition or bindings to the according status requests (probably due to targeting embedded area).

Will link the PR.
