### ISSUE TITLE
Can't upgrade 0.22.0 -> 0.22.2 because of new bitflags requirement.

### ISSUE THREAD

**Issue by m-ou-se** [nix-rust/nix#1548]
`cargo deny check` just informed me about [RUSTSEC-2021-0119](https://rustsec.org/advisories/RUSTSEC-2021-0119). My dependencies are using 0.22.0, and should be upgraded to the patched 0.22.2.

However, nix 0.22.0 requires `bitflags ^1.1`, but nix 0.22.1 and 0.22.2 require `bitflags >= 1.1.0, < 1.3.0`.

Cargo refuses to use multiple *semver compatible* versions of a crate in a dependency tree (see [this comment](https://github.com/rust-lang/cargo/issues/6584#issuecomment-457245362)), so any dependency tree requiring `bitflags ^1.3` anywhere cannot upgrade from 0.22.0 to 0.22.2.

For example, `i2cdev` [requires](https://github.com/rust-embedded/rust-i2cdev/blob/master/Cargo.toml):
```toml
bitflags = "1.3"
nix = "0.22"
```
which can only work with 0.22.0, and not with 0.22.1 or 0.22.2.

**Comment by asomers** [comment]
This is a bug in bitflags that's been causing a lot of pain for everyone.  They raised their MSRV in a minor version release.  Your choices are to upgrade to Nix 0.23 or to remain on Nix 0.22.0 and suppress that RUSTSEC warning.  The RUSTSEC warning only applies to a single function, and it's not an exploitable security problem, so that may be an option for you.
https://github.com/bitflags/bitflags/issues/255
