### ISSUE TITLE
Proposal: allow unused_imports

### ISSUE THREAD

**Issue by SUPERCILEX** [nix-rust/nix#1929]
The `unused_imports` deny is deeply annoying. There are both overlapping and non-overlapping sets of platforms that need different imports and it sucks to try and satisfy those requirements, especially since you can only really tell when an import's gone bad if CI yells at you.

I'd like to propose allowing all unused_imports. Thoughts?

**Comment by SUPERCILEX** [comment]
cc @asomers @rtzoeller

**Comment by SUPERCILEX** [comment]
Mmmm, now I'm actually not sure if this is a good idea. Or at least, it seems like if we allow `unused_imports` we should just allow any unused. Maybe that's not a bad idea? I wish there was a way to say "tell me if this is unused across all platforms and features" since that's what we actually care about.

**Comment by asomers** [comment]
Yeah, I wrestled with this problem too, when I first added features.  That's why I added `#[allow(unused_imports)]` if the `default` feature is enabled.  But I couldn't find a good way to say "allow imports that are used on at least one platform".  Unless we can do that, I think we need to keep denying unused imports.

**Comment by SUPERCILEX** [comment]
Yeah, it's sad but I think I agree. Bummer.
