### ISSUE TITLE
Export all symbols at crate root as in libc

### ISSUE THREAD

**Issue by kamalmarhubi** [nix-rust/nix#214]
As part of implementing [RFC 1291](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md), the structure of the libc crate was changed. It now exports all symbols at the top level. I think it's worth considering the same structure for nix.

**Comment by Susurrus** [comment]
I don't think this makes sense, primarily from a documentation point of view. It's nice being able to provide docs for entire modules for some of the wrapper types that `nix` implements. It also makes it easier for people from from C to find the man pages. I think it made sense for `libc` to do this given that they don't care about documentation as they're such a low-level dependency, but for `nix` we want to have a really good documentation story that includes being able to reuse all the existing docs on libc stuff.

I'm closing this as a WONTFIX because of the above.
