### ISSUE TITLE
`ru_maxrss` in the result of `getrusage` is in bytes on macOS

### ISSUE THREAD

**Issue by hanwentao** [nix-rust/nix#2331]
According to the manpage of `getrusage` on macOS, `ru_maxrss` is in bytes, which contradicts the statement in nix's doc.

Quote from `man getrusage` on macOS:

> ru_maxrss    the maximum resident set size utilized (in bytes).

nix's doc on `Usage`:

> The resident set size at its peak, in kilobytes.

**Comment by SteveLauC** [comment]
Thanks for reporting this! This issue is interesting.

> According to the manpage of getrusage on macOS, ru_maxrss is in bytes, which contradicts the statement in nix's doc.

The [online man page](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html), says it is in kilobytes. But a newer version of [man pages](https://keith.github.io/xcode-man-pages/getrusage.2.html) (extracted from Xcode by a community user), says that it is in bytes.

I guess that Apple changed this interface in a specific version, a rough search leads me to this [post](https://stackoverflow.com/questions/59913657/strange-values-of-get-rusage-maxrss-on-macos-and-linux), it seems that this change has been made for more than 4 years.
