### ISSUE TITLE
Add syslog APIs

### ISSUE THREAD

**Issue by lambda-fairy** [nix-rust/nix#413]
The [syslog interfaces](http://linux.die.net/man/3/syslog) are useful for writing daemons and such. It would be nice to have bindings to them.

**Comment by lfairy** [comment]
I've published a preliminary set of bindings on [my fork](https://github.com/lfairy/nix/blob/syslog/src/syslog.rs). There are a few issues with it so far:

* According to the [Linux documentation](http://linux.die.net/man/3/syslog), the `ident` argument to `openlog()` should have a static lifetime. I have modeled this using `&'static CStr`, which is correct but kind of fiddly.

* The interface of `syslog()` itself *almost* matches that of `printf`, except the former supports an extra code `%m`. I have no idea how to expose this safely.

Given these issues, I think we'd be better off just using a pure-Rust implementation instead.

**Comment by fiveop** [comment]
> I have modeled this using &'static CStr, which is correct but kind of fiddly.

I think is the correct way to expose it safely.

> The interface of syslog() itself almost matches that of printf, except the former supports an extra code %m. I have no idea how to expose this safely.

I have not encountered a good way of dealing with foreign functions with a variable number of arguments. When strings are involved, it only gets messier.

**Comment by lfairy** [comment]
> I have not encountered a good way of dealing with foreign functions with a variable number of arguments. When strings are involved, it only gets messier.

A syntax extension would work, but I think that would be overkill for this crate.

**Comment by tisonkun** [comment]
> I think we'd be better off just using a pure-Rust implementation instead.

A binding is still helpful.

Today, I tried to write syslogs to macos, and encounter this issue https://github.com/python/cpython/issues/91070, while directly call `syslog(3)` can work.

**Comment by tisonkun** [comment]
Or from the other perspective, how to implement syslog lib as in rust?

I made https://github.com/fast/fasyslog/ as a syslog client library. It works well for remote server and if the syslog daemon listens to a UNIX domain socket. But macos no longer works in either way so it's hard to make it work on macos.

**Comment by SteveLauC** [comment]
> A binding is still helpful.

> while directly call syslog(3) can work.

Considering that macOS bug, I agree it would be still helpful to bind them, if we can safely do so.

**Comment by tisonkun** [comment]
Ref -

* https://github.com/python/cpython/blob/v3.13.0/Modules/clinic/syslogmodule.c.h#L112
* https://github.com/python/cpython/blob/v3.13.0/Modules/syslogmodule.c

**Comment by tisonkun** [comment]
> The interface of syslog() itself almost matches that of printf, except the former supports an extra code %m. I have no idea how to expose this safely. EDIT: printf supports this code as well.

I don't think we need to support the C formatter. Rust has its own format functions and we can also pass the formatted string without any other format signs.

**Comment by AlexTMjugador** [comment]
> Given these issues, I think we'd be better off just using a pure-Rust implementation instead.

I figured I'd give my two cents about this idea, because how `syslog` works in detail seems to be an overall pretty obscure topic on the Internet and I did not see this point being stressed (enough? [This](https://unix.stackexchange.com/questions/205883/understand-logging-in-linux) is probably the only good summary I found about it): almost every Unix flavor under the sun I've looked into has a different implementation of the `syslog` functions.

[Linux](https://www.gnu.org/software/libc/manual/html_node/syslog_003b-vsyslog.html) [ones](https://github.com/esmil/musl/blob/194f9cf93da8ae62491b7386edf481ea8565ae4e/src/misc/syslog.c#L28-L34) communicate with a Unix datagram socket at `/dev/log`, [FreeBSD](https://github.com/freebsd/freebsd-src/blob/0b4c4833ee3eab0ce46b3bdbf054bca4b6bb7429/sys/sys/syslog.h#L35) with a Unix datagram socket at `/var/run/log`, [Solaris](https://github.com/kofemann/opensolaris/blob/80192cd83bf665e708269dae856f9145f7190f74/usr/src/lib/libast/common/comp/syslog.c#L44-L53) attempts several Unix stream sockets beginning with `/var/log/syslog`, newer MacOS versions don't even log to a socket anymore and instead [forward logs to `os_log`](https://github.com/rigetti/rpcq/issues/92#issuecomment-528197906) (but only if you call the right versioned symbol)... The [POSIX standard](https://pubs.opengroup.org/onlinepubs/9799919799/functions/syslog.html) is as vague as it gets about actual implementation details.

So, if we are to rewrite it in Rust, we should be aware that are years of different conventions and use cases formed around practical implementations of this function we should care about, and getting it to work portably just right is thus more involved than the simplicity of the interface may suggest at a first glance.
