### ISSUE TITLE
Provide clearenv?

### ISSUE THREAD

**Issue by shahn** [nix-rust/nix#481]
Can clearenv() be supported, with a workaround of environ = NULL where it's not supported?

**Comment by fiveop** [comment]
Certainly (at least for the first part). You would need to add bindings for `clearenv` to the project [libc](https://github.com/rust-lang/libc) and then add a wrapper to nix.

As for the latter part, you would need to figure out (for each platform) how to implement `clearenv` given the capabilities provided by libc.

**Comment by Susurrus** [comment]
`clearenv` is already in `libc`, so this just needs a safe wrapper.

**Comment by wginolas** [comment]
I am thinking about implementing this feature, but I am not sure where to add the cleanenv () implementation. Are there any other functions concerning environment variables?

**Comment by Susurrus** [comment]
Cool, it'd be great to implement this! If you look at [the man page](http://man7.org/linux/man-pages/man3/clearenv.3.html), you'll see that `clearenv(3)` is a Linux-only API, but it has a few sibling functions that should also be implemented and are POSIX: `getenv(3)`, `putenv(3)`, `setenv(3)`, and `unsetenv(3)`.

As to where to put these functions, we normally put functions into files following their location within `libc` (you can use the manpages to figure out which files functions are in). But for `stdlib.h` we've been splitting up the `stdlib.h` header into separate files, and I think it makes sense to continue this. I'd suggest you put all these functions into a `src/env.rs` file.

And if you get stuck while writing code, I'd suggest submitting a draft PR (put [WIP] in the title if you don't want us to comment yet and are just running CI or the like) and we'll review it rather than continuing discussion here.
