### ISSUE TITLE
Is it possible to change the license for nix to MIT/APACHE?

### ISSUE THREAD

**Issue by vishvananda** [nix-rust/nix#570]
I'm hoping to use the apache license for some code that uses this library. While it is possible to use mit licensed code in an apache project, it is simpler if both licenses are allowed. The majority of the rust ecosystem allows for both licenses.

**Comment by Susurrus** [comment]
MIT is a more permissive license than Apache2, so there's no problem using this code with Apache2, but IANAL. You shouldn't be prevented from doing what you want based on a license change.

cc @nix-rust/nix-maintainers Any thoughts here?

**Comment by kamalmarhubi** [comment]
IANAL either. My unfounded belief is we'd need to get approval from every one of the ~100 contributors to relicense their work. @carllerche do you have thoughts?

**Comment by notriddle** [comment]
According to [the Rust FAQ, they use the MIT/Apache license because](https://www.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license):

> The Apache license includes important protection against patent aggression, but it is not compatible with the GPL, version 2. To avoid problems using Rust with GPL2, it is alternately MIT licensed.

**Comment by Susurrus** [comment]
I'm much more a fan of the Mozilla Public License 2.0. It's basically GPL but the segregation of code occurs at the file level instead at a binary interface, which is problematic for Rust where almost all code is statically compiled. It's what I've licensed all my Rust crates.

**Comment by posborne** [comment]
Although I would not stand in the way of a license change, I see no strong reason to relicense from the MIT license to a dual license scheme given the amount of work that I perceive would be required.

Although I prefer the MPL to the GPL, I am generally most interested in MIT/Apache licensed projects that can provide the greatest value to the greatest number of people/entities.

**Comment by utkarshkukreti** [comment]
One benefit of having a dual MIT/Apache-2.0 license is that Rust, Cargo, and other projects under rust-lang{,-nursery} will be able to freely take code from nix without having to change their license to say that "this piece of code is just MIT, not MIT/Apache-2.0".

**Comment by Susurrus** [comment]
@utkarshkukreti That's not how licenses work. Since the MIT license is less restrictive, you can use the MIT license in an MIT/Apache2 project without any issue because you can ass the Apache2 license on top of it. That's one of the things that the MIT license allows you to do. This issue was filed based on a misunderstanding of how licensing works but is actually a nonissue.

I'm closing this issue because a) the use case for the OP is currently possible with the current licensing scheme and b) there is no interest on the behalf of the maintainers to alter the licensing to something else given the logistical problems it entails.

**Comment by utkarshkukreti** [comment]
@Susurrus I'm not sure what you mean by "add" here. You definitely cannot copy MIT licensed code to an MIT/Apache-2.0 dual licensed code and then release the _whole_ code under MIT/Apache-2.0.

**Comment by Susurrus** [comment]
Sorry, I phrased that oddly. How I should have phrased it is that you can currently distribute MIT-licensed code under the Apache-2.0 license because the terms of the Apache-2.0 license also fulfill the requirements of the MIT license. The same will hold true for a project licensed as MIT/Apache-2.0. In fact, you can distribute MIT-licensed code under any additional license you so choose as long as you continue to fulfill the terms of that license (which is just a copyright header). This is because MIT (actually Apache-2.0 also) are not copy-left (aka viral) and do not require projects using their code to maintain the same license.

**Comment by utkarshkukreti** [comment]
Yes, you can distribute the resulting code (unlike GPL) but the resulting code will then be licensed as \<old license> for everything except the copied code and MIT license for the copied code.

**Comment by Susurrus** [comment]
I actually think that you should be able to relicense the code as long as you use an equivalent or more restrictive license such that you still fulfill the obligations of the MIT license. For example, you should be able to relicense MIT code as Apache-2.0 because it fulfills all of the MIT license requirements and therefore treat that code as Apache-2.0 code.

**Comment by utkarshkukreti** [comment]
The Apache-2.0 license includes a Patent Grant which the MIT license doesn't: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

Also, if we could just re-license MIT to Apache-2.0, we wouldn't need any permission from the 100+ contributors. :)

**Comment by kamalmarhubi** [comment]
I think the only options to consider here are:
1. do nothing (remain MIT-only)
2. attempt to dual-license under MIT/APL-2.0

The first takes no effort. I'm reasonably sure the second would require the permission of all contributors,

**Comment by kamalmarhubi** [comment]
I missed that this was closed. Ignore me.
