### ISSUE TITLE
Implement fallocate(2)

### ISSUE THREAD

**Issue by agrover** [nix-rust/nix#596]
See man 2 fallocate. I think this should be relatively straightforward (at least I hope so.)

**Comment by Susurrus** [comment]
@agrover Would you be willing to submit a PR adding this functionality? I'd be willing to mentor it through the process.

There's also `posix_fallocate(3)` for a more-portable version, but I don't know how similar those are.

**Comment by SanchayanMaity** [comment]
@Susurrus As a beginner in rust, is this something I can take up? Would you mentor me and point me in the right direction to get started?

**Comment by Susurrus** [comment]
Yeah, id be happy to mentor and get you started. The first step is for you to read over the CONTRIBUTING.md document which should cover the basics. Additionally you should read the man pages for fallocate and make sure you understand the API. After those things Please post back here if you have any fundamental questions. Otherwise just go ahead and open a PR and we can iterate there.

**Comment by agrover** [comment]
fixed by #768, thanks!!
