### ISSUE TITLE
Add prctl(2) support

### ISSUE THREAD

**Issue by cyphar** [nix-rust/nix#601]
I'm working on an [alternative container init and signal forwarder](https://github.com/cyphar/initrs), and a nice feature would be to be able to run it as non-pid1. However, that requires being able to set PR_SET_CHILD_SUBREAPER from within Rust.

While it's possible to do this:

```rust
use libc::{prctl, PR_SET_CHILD_SUBREAPER};
unsafe { prctl(PR_SET_CHILD_SUBREAPER, 1, 0, 0); }
```

The `unsafe` is unsightly.

**Comment by Susurrus** [comment]
Indeed, it seems reasonable to add `prctl(2)`. Would you be willing to submit a PR for this?

**Comment by cyphar** [comment]
I'm not a very proficient user of Rust yet (I just started picking it up last weekend), but I believe that [the `prctl` crate](https://github.com/viraptor/prctl-rs) could be a reasonable starting point. The biggest thing that makes `prctl(2)` ugly and unsafe is that the arguments are sometimes read and sometimes written to by the kernel.

**Comment by Susurrus** [comment]
If you want to have a go at it, I'll mentor you. This crate does very low level abstractions, so basically what you already wrote puts you half way there I'd think. We wouldn't try to offer a more comprehensive high-level API as that crate seems to be aiming for. Otherwise I don't know how likely it is for someone to tackle this in the near future.

**Comment by SteveLauC** [comment]
Close as completed in #1550
