### ISSUE TITLE
siginfo_t needs more fields

### ISSUE THREAD

**Issue by MarkSwanson** [nix-rust/nix#628]
I need to access siginfo_t.si_syscall from inside a sigaction (SIGSYS / SA_SIGINFO).
Unfortunately this doesn't seem to be possible ootb because nix uses libc::siginfo_t, which doesn't provide si_syscall.

Recommendations for accessing si_syscall without forking nix?

Thanks!

**Comment by Susurrus** [comment]
You'll need to bring this up with the `libc` crate it looks like, since that's actually the root of the issue. It'd also help for here and for the issue you'll open on the `libc` crate to have example code demonstrating what you'd like to do (or maybe a C implementation), which should make things more clear.

But you could use `unsafe` and transmute the memory into a custom designed local struct for your needs. Even though `libc` doesn't expose a complete struct, you can implement that struct yourself and then transmute from the `libc` struct to yours and then access the field directly.

That being said, it would be appreciated if you submit a PR to `libc` fixing this issue for your use case so that `nix` can then work for you as well.

**Comment by MarkSwanson** [comment]
Ty for your suggestions.
Will try to find the time to submit a PR.
